FROM node:24-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:24-alpine AS runtime
WORKDIR /app
RUN apk add --no-cache curl
COPY --from=build /app/dist/frontend ./
EXPOSE 4000
CMD [ "node", "server/server.mjs" ]